### ISSUE TITLE
Errors in tests

### ISSUE THREAD

**Issue by otis22** [otis22/vetmanager-botman#75]
There were 2 errors:

1) Tests\Unit\Vetmanager\MessageBuilder\Timesheet\TimesheetMessageBuilderTest::testBuildMessage
Error: Class 'App\Vetmanager\MessageBuilder\Admission\TimesheetMessageBuilder' not found

/home/runner/work/vetmanager-botman/vetmanager-botman/tests/Unit/Vetmanager/MessageBuilder/Timesheet/TimesheetMessageBuilderTest.php:20

2) Tests\Unit\Vetmanager\MessageBuilder\Timesheet\TimesheetMessageBuilderTest::testBuildMessageWithEmptyTimesheet
Error: Class 'App\Vetmanager\MessageBuilder\Admission\TimesheetMessageBuilder' not found

/home/runner/work/vetmanager-botman/vetmanager-botman/tests/Unit/Vetmanager/MessageBuilder/Timesheet/TimesheetMessageBuilderTest.php:33

ERRORS!

**Comment by danilyer228** [comment]
@otis22 need composer update
